### ISSUE TITLE
‘struct usb_interface’ has no member named ‘pm_usage_cnt’

### ISSUE THREAD

**Issue by wjakiela** [lwfinger/rtl8723au_bt#71]
rtk_btusb.c:873:79: error: ‘struct usb_interface’ has no member named ‘pm_usage_cnt’

https://github.com/raspberrypi/linux/commit/83c6688d679c1d95ed79650f4ec6e702548c39ef#diff-d81b85761c12e5ebdcaca4309ff73cfe

**Comment by MdHusainhfz** [comment]
in file include/linux/usb.h, search " struct usb_interface { " 
and add " atomic_t pm_usage_cnt; "  before the }

**Comment by lwfinger** [comment]
What kernel are you using? I just did a build with kernel 6.1.1, and it built correctly.
