### ISSUE TITLE
Package Version number for dkms?

### ISSUE THREAD

**Issue by tonywhelan** [lwfinger/rtl8723au_bt#68]
Thank you for your work with this driver. I would like to install it with DKMS so that the driver persists if there is a kernem upgrade. Have tried setting it up with DKMS but dkms.conf requires a PACKAGE_VERSION number and I have no idea what/where that is. 

I have been able to use the DKMS instructions for the rtl8723au wifi driver, but am stymied at present with what to use for rtl8723au_bt
-------------------------
EDIT: Version 0.1 seems to be it 
but I get an error: 
 
make KERNELRELEASE=4.13.0-26-generic -C /lib/modules/4.13.0-26-generic/build M=/var/lib/dkms/8723au_bt/0.1/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.13.0-26-generic (x86_64)
Consult /var/lib/dkms/8723au_bt/0.1/build/make.log for more information

and the log says:

make: Entering directory '/usr/src/linux-headers-4.13.0-26-generic'
  AR      /var/lib/dkms/8723au_bt/0.1/build/built-in.o
  CC [M]  /var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.o
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c:41:2: error: #error "This repo is only for kernels older than 4.1.0. For kernel 4.1 or later, use the kernel branch."
 #error "This repo is only for kernels older than 4.1.0. For kernel 4.1 or later, use the kernel branch."
  ^
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c: In function ‘btusb_intr_complete’:
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c:168:7: error: implicit declaration of function ‘hci_recv_fragment’ [-Werror=implicit-function-declaration]
   if (hci_recv_fragment(hdev, HCI_EVENT_PKT,
       ^
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c: In function ‘btusb_close’:
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c:575:18: error: ‘NUM_REASSEMBLY’ undeclared (first use in this function)
  for (i = 0; i < NUM_REASSEMBLY; i++) {
                  ^
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c:575:18: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c:576:10: error: ‘struct hci_dev’ has no member named ‘reassembly’
   if(hdev->reassembly[i]) {
          ^
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c:577:18: error: ‘struct hci_dev’ has no member named ‘reassembly’
    kfree_skb(hdev->reassembly[i]);
                  ^
/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.c:578:8: error: ‘struct hci_dev’ has no member named ‘reassembly’
    hdev->reassembly[i] = NULL;
        ^
cc1: some warnings being treated as errors
scripts/Makefile.build:315: recipe for target '/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.o' failed
make[1]: *** [/var/lib/dkms/8723au_bt/0.1/build/rtk_btusb.o] Error 1
Makefile:1550: recipe for target '_module_/var/lib/dkms/8723au_bt/0.1/build' failed
make: *** [_module_/var/lib/dkms/8723au_bt/0.1/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.13.0-26-generic'

The error "This repo is only for kernels older than 4.1.0. For kernel 4.1 or later, use the kernel branch.." looks to be the cause. But I am unsure about whether this error is something that can/should be bypassed.
